### PR TITLE
Downgrade from .NET 7 to .NET 6 support

### PR DESCRIPTION
**Pull request by ghost**
Description:
This pull request downgrades the project from .NET 7 to .NET 6 support. The decision to revert back to .NET 6 was made to ensure compatibility with existing dependencies and maintain a stable development environment. The necessary changes have been implemented to adapt the project accordingly. Please review and merge this pull request.

Changes Made:

Updated project configuration to target .NET 6 framework
Removed any references or code specific to .NET 7

### CODE REVIEW

**Review by Aaronontheweb — APPROVED** [review]
LGTM - I don't see any harm in downgrading to .NET 6.0.

**Comment by Aaronontheweb** [comment]
@pavleda you might need to update `global.json` to target .NET 6 in order to get the tests to pass, if they fail after this first run.

**Comment by ghost** [comment]
Hey @Aaronontheweb, since it's my first time contributing to the OS package, how can a downgraded version be released?

**Comment by Aaronontheweb** [comment]
I'll type up some release notes and push a new tag - that will create a new NuGet release.

Sorry for the delay - been traveling this week.

**Comment by Aaronontheweb** [comment]
Ok, just pushed the tag - new package should go live in the next 30 minutes or so (depends mostly on how fast CI runs)

**Pull request merged**
